local addonName, ns = ...

ns.GUI = ns.GUI or {}
ns.GUI.Layouts = ns.GUI.Layouts or {}

ns.GUI.Layouts.UnitFrame = ns.GUI.Layouts.UnitFrame or {}

ns.GUI.Layouts.UnitFrame.Lists = {
    anchorPoints = {
        TOPLEFT = "VALUE_ANCHOR_TOPLEFT",
        TOP = "VALUE_ANCHOR_TOP",
        TOPRIGHT = "VALUE_ANCHOR_TOPRIGHT",
        LEFT = "VALUE_ANCHOR_LEFT",
        CENTER = "VALUE_ANCHOR_CENTER",
        RIGHT = "VALUE_ANCHOR_RIGHT",
        BOTTOMLEFT = "VALUE_ANCHOR_BOTTOMLEFT",
        BOTTOM = "VALUE_ANCHOR_BOTTOM",
        BOTTOMRIGHT = "VALUE_ANCHOR_BOTTOMRIGHT",
    },
    frameStrata = {
        BACKGROUND = "VALUE_FRAME_STRATA_BACKGROUND",
        LOW = "VALUE_FRAME_STRATA_LOW",
        MEDIUM = "VALUE_FRAME_STRATA_MEDIUM",
        HIGH = "VALUE_FRAME_STRATA_HIGH",
        DIALOG = "VALUE_FRAME_STRATA_DIALOG",
        FULLSCREEN = "VALUE_FRAME_STRATA_FULLSCREEN",
        FULLSCREEN_DIALOG = "VALUE_FRAME_STRATA_FULLSCREEN_DIALOG",
        TOOLTIP = "VALUE_FRAME_STRATA_TOOLTIP",
    },
}
